Add Chinese Generation Task
chancefocus/PIXIU pull request #36
Opened 2023-10-23 15:37 UTC by YY0649

2023-10-23 15:41 UTC, jiminHuang requested changes

2023-10-23 15:41 UTC, jiminHuang commented on src/tasks/__init__.py
> -    "flare_zh_stockb": flare.ZHstock11,
Why stockb is removed?

2023-10-23 15:41 UTC, jiminHuang commented on src/tasks/flare.py
> +        for gold_item in golds:
is it intersection? You can directly use & to calculate

2023-10-23 15:41 UTC, jiminHuang commented on src/tasks/zhutils.py
> +    entity_list = [(", ".join(val.split(", ")[:-1]), val.split(", ")[-1]) for val in formatted_result.split("\n")]
Should we consider the Chinese ，

2023-10-27 13:44 UTC, jiminHuang commented on src/tasks/flare.py
> +                if gold_item & pred_item:
The `process` returns two sets?

2023-10-29 20:23 UTC, xashely approved these changes

2023-10-29 20:24 UTC, jiminHuang approved these changes

2023-10-29 20:24 UTC, merged